---
# Cassandra Ansible Playbook
- hosts: cassandra_nodes:children
  user: ubuntu
  become: yes
  vars:
    init_server: true
    empty_cluster: true
    cluster_name: cassandra_cluster_1
    num_tokens: 256
    proxy_env:
      http_proxy: ''
      https_proxy: ''
      no_proxy: 'localhost,127.0.0.1'

  roles:
    - { role: cassandra_common, tags: ['cassandra_common'] }
    - { role: cassandra, tags: ['cassandra'] }
    - { role: opscenter, tags: ['opscenter'], when: install_version == "dse" and (opscenter_enabled | default(false)) == "true"  }
    - { role: cassandra_cron, tags: ['cron'] }
